language: node_js
node_js:
  - 5
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - libstdc++-4.8-dev
cache:
  directories:
    - node_modules
before_install:
  - export PATH="$HOME/.local/bin:./node_modules/.bin:$PATH"
  - export CXX="g++-4.8" CC="gcc-4.8"
install:
  - npm install
  - npm update
  - npm run build
script:
  - npm run lint
